/** Generate the Swift transport constants and first typed Host response from the native protocol manifest. */

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

interface Manifest {
  protocolVersion: number
  capabilities: string[]
  hostDescription: {
    required: Record<string, string>
    optional: Record<string, string>
  }
}

const root = resolve(import.meta.dirname, '..')
const manifest = JSON.parse(
  readFileSync(resolve(root, 'Protocol/native-client-protocol.json'), 'utf8'),
) as Manifest

const fields = [
  ...Object.entries(manifest.hostDescription.required).map(([name, type]) => `    public let ${name}: ${type}`),
  ...Object.entries(manifest.hostDescription.optional).map(([name, type]) => `    public let ${name}: ${type}?`),
].join('\n')

const output = `// Generated by scripts/generate-swift-protocol.ts. Do not edit.\n\nimport Foundation\n\npublic enum NativeProtocol {\n    public static let version = ${String(manifest.protocolVersion)}\n    public static let capabilities = ${JSON.stringify(manifest.capabilities)}\n}\n\npublic struct HostDescription: Codable, Equatable, Sendable {\n${fields}\n}\n`

writeFileSync(
  resolve(root, 'Sources/DshNativeProtocol/ProtocolVersion.generated.swift'),
  output,
)
