// Generated by scripts/generate-swift-protocol.ts. Do not edit.

import Foundation

public enum NativeProtocol {
    public static let version = 0
    public static let capabilities = ["rpc.unary","rpc.respond","events.mux","events.host"]
}

public struct HostDescription: Codable, Equatable, Sendable {
    public let version: String
    public let cwd: String
    public let attachedSessions: Int
    public let canOpenPath: Bool
    public let provider: String?
    public let model: String?
}
